# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
script: 
  - R -e "devtools::install(dep=TRUE)"
  - R -e 'lapply(list.files(pattern=".*.Rmd", recursive=TRUE), rmarkdown::render)'


## Alternate recipe: use Docker instead of R travis
#sudo: required
#services:
#  - docker
#script:
#  - docker run -ti -v $(pwd):/home/rstudio/repo -w /home/rstudio/repo \
#    rocker/verse:3.4.2 \
#    R -e 'lapply(list.files(pattern=".*.Rmd", recursive=TRUE), rmarkdown::render)'


